spring.application.name=ride-share-backend

# Server Configuration
server.port=${PORT:8080}

# SQLite Configuration
spring.datasource.url=jdbc:sqlite:rideshare.db
spring.datasource.driver-class-name=org.sqlite.JDBC
spring.jpa.database-platform=org.hibernate.community.dialect.SQLiteDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# Mail Configuration
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=vishnuthakur0541@gmail.com
spring.mail.password=wggncspmhufenjjk
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
# JWT Configuration (Secret key should be at least 256 bits / 32 characters)
jwt.secret=5367566B59703373367639792F423F4528482B4D6251655468576D5A71347437

logging.level.org.springframework.security=DEBUG
logging.level.org.springframework.web=DEBUG
